apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: design
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
images:
- name: nginx
  newName: registry.home.jrbeverly.dev/jrbeverl/common
  newTag: design-20742-1672840042
