apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - storage.yaml
  - namespace.yaml
  # jackett
  - jackett-config.yaml
  - jackett.yaml
  - radarr.yaml
  - sonarr.yaml
  - transmission.yaml
  # emby