apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv
spec:
  capacity:
    storage: 5000G
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Delete
  storageClassName: media-local-storage
  local:
    path: /srv/media
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - homeserver
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-claim
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5000G
  storageClassName: media-local-storage