---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emby-config
  namespace: emby
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 128Mi
