apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gitlab-secret-store
  namespace: actions-runner-system
spec:
  provider:
    gitlab:
      auth:
        SecretRef:
          accessToken:
            name: gitlab-secret
            key: token
      projectID: "35986680"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-app
  namespace: actions-runner-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: gitlab-secret-store
  target:
    name: controller-manager
    creationPolicy: Owner
  data:
    - secretKey: github_app_id
      remoteRef: 
        key: GITHUB_APP_ID
    - secretKey: github_app_installation_id
      remoteRef: 
        key: GITHUB_APP_INSTALLATION_ID
    - secretKey: github_app_private_key
      remoteRef: 
        key: GITHUB_APP_PRIVATE_KEY